[package]
name = "extension"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda-extension = "0.11.0"
mockall = "0.13.1"
opentelemetry = "0.29.1"
serde = "1"
tokio = { version = "1", features = ["macros"] }
tokio-util = "0.7.15"
